#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reconocimiento_facial
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Faces")]
	public partial class LinqDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertAdmin(Admin instance);
    partial void UpdateAdmin(Admin instance);
    partial void DeleteAdmin(Admin instance);
    partial void InsertUserFaces(UserFaces instance);
    partial void UpdateUserFaces(UserFaces instance);
    partial void DeleteUserFaces(UserFaces instance);
    partial void Insertasistencia(asistencia instance);
    partial void Updateasistencia(asistencia instance);
    partial void Deleteasistencia(asistencia instance);
    partial void InsertDocentes(Docentes instance);
    partial void UpdateDocentes(Docentes instance);
    partial void DeleteDocentes(Docentes instance);
    partial void InsertEstado(Estado instance);
    partial void UpdateEstado(Estado instance);
    partial void DeleteEstado(Estado instance);
    partial void Insertfecha(fecha instance);
    partial void Updatefecha(fecha instance);
    partial void Deletefecha(fecha instance);
    partial void InsertJustificacion(Justificacion instance);
    partial void UpdateJustificacion(Justificacion instance);
    partial void DeleteJustificacion(Justificacion instance);
    #endregion
		
		public LinqDataDataContext() : 
				base(global::Reconocimiento_facial.Properties.Settings.Default.FacesConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public LinqDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Admin> Admin
		{
			get
			{
				return this.GetTable<Admin>();
			}
		}
		
		public System.Data.Linq.Table<UserFaces> UserFaces
		{
			get
			{
				return this.GetTable<UserFaces>();
			}
		}
		
		public System.Data.Linq.Table<asistencia> asistencia
		{
			get
			{
				return this.GetTable<asistencia>();
			}
		}
		
		public System.Data.Linq.Table<Docentes> Docentes
		{
			get
			{
				return this.GetTable<Docentes>();
			}
		}
		
		public System.Data.Linq.Table<Estado> Estado
		{
			get
			{
				return this.GetTable<Estado>();
			}
		}
		
		public System.Data.Linq.Table<fecha> fecha
		{
			get
			{
				return this.GetTable<fecha>();
			}
		}
		
		public System.Data.Linq.Table<Justificacion> Justificacion
		{
			get
			{
				return this.GetTable<Justificacion>();
			}
		}
		
		public System.Data.Linq.Table<Asistencia_View> Asistencia_View
		{
			get
			{
				return this.GetTable<Asistencia_View>();
			}
		}
		
		public System.Data.Linq.Table<Info_docente> Info_docente
		{
			get
			{
				return this.GetTable<Info_docente>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertar_asignatura", IsComposable=true)]
		public object insertar_asignatura([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string asignatura)
		{
			return ((object)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), asignatura).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertar_docente")]
		public int insertar_docente([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(80)")] string identificador)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre, identificador);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.procedimiento")]
		public ISingleResult<procedimientoResult> procedimiento([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(10)")] string iddocente, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(10)")] string dia)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iddocente, dia);
			return ((ISingleResult<procedimientoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.procedimiento2")]
		public ISingleResult<procedimiento2Result> procedimiento2([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> iddocente, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(10)")] string fecha)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iddocente, fecha);
			return ((ISingleResult<procedimiento2Result>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Admin")]
	public partial class Admin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _User;
		
		private string _contrasena;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnUserChanging(string value);
    partial void OnUserChanged();
    partial void OncontrasenaChanging(string value);
    partial void OncontrasenaChanged();
    #endregion
		
		public Admin()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[User]", Storage="_User", DbType="NVarChar(30)")]
		public string User
		{
			get
			{
				return this._User;
			}
			set
			{
				if ((this._User != value))
				{
					this.OnUserChanging(value);
					this.SendPropertyChanging();
					this._User = value;
					this.SendPropertyChanged("User");
					this.OnUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contrasena", DbType="NVarChar(30)")]
		public string contrasena
		{
			get
			{
				return this._contrasena;
			}
			set
			{
				if ((this._contrasena != value))
				{
					this.OncontrasenaChanging(value);
					this.SendPropertyChanging();
					this._contrasena = value;
					this.SendPropertyChanged("contrasena");
					this.OncontrasenaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UserFaces")]
	public partial class UserFaces : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdImage;
		
		private System.Data.Linq.Binary _Face;
		
		private System.Nullable<int> _id_docente;
		
		private EntityRef<Docentes> _Docentes;
		
		private EntityRef<Docentes> _Docentes1;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdImageChanging(int value);
    partial void OnIdImageChanged();
    partial void OnFaceChanging(System.Data.Linq.Binary value);
    partial void OnFaceChanged();
    partial void Onid_docenteChanging(System.Nullable<int> value);
    partial void Onid_docenteChanged();
    #endregion
		
		public UserFaces()
		{
			this._Docentes = default(EntityRef<Docentes>);
			this._Docentes1 = default(EntityRef<Docentes>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdImage", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdImage
		{
			get
			{
				return this._IdImage;
			}
			set
			{
				if ((this._IdImage != value))
				{
					this.OnIdImageChanging(value);
					this.SendPropertyChanging();
					this._IdImage = value;
					this.SendPropertyChanged("IdImage");
					this.OnIdImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Face", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Face
		{
			get
			{
				return this._Face;
			}
			set
			{
				if ((this._Face != value))
				{
					this.OnFaceChanging(value);
					this.SendPropertyChanging();
					this._Face = value;
					this.SendPropertyChanged("Face");
					this.OnFaceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_docente", DbType="Int")]
		public System.Nullable<int> id_docente
		{
			get
			{
				return this._id_docente;
			}
			set
			{
				if ((this._id_docente != value))
				{
					if ((this._Docentes.HasLoadedOrAssignedValue || this._Docentes1.HasLoadedOrAssignedValue))
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_docenteChanging(value);
					this.SendPropertyChanging();
					this._id_docente = value;
					this.SendPropertyChanged("id_docente");
					this.Onid_docenteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Docentes_UserFaces", Storage="_Docentes", ThisKey="id_docente", OtherKey="id_docente", IsForeignKey=true, DeleteRule="CASCADE")]
		public Docentes Docentes
		{
			get
			{
				return this._Docentes.Entity;
			}
			set
			{
				Docentes previousValue = this._Docentes.Entity;
				if (((previousValue != value) 
							|| (this._Docentes.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Docentes.Entity = null;
						previousValue.UserFaces.Remove(this);
					}
					this._Docentes.Entity = value;
					if ((value != null))
					{
						value.UserFaces.Add(this);
						this._id_docente = value.id_docente;
					}
					else
					{
						this._id_docente = default(Nullable<int>);
					}
					this.SendPropertyChanged("Docentes");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Docentes_UserFaces1", Storage="_Docentes1", ThisKey="id_docente", OtherKey="id_docente", IsForeignKey=true)]
		public Docentes Docentes1
		{
			get
			{
				return this._Docentes1.Entity;
			}
			set
			{
				Docentes previousValue = this._Docentes1.Entity;
				if (((previousValue != value) 
							|| (this._Docentes1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Docentes1.Entity = null;
						previousValue.UserFaces1.Remove(this);
					}
					this._Docentes1.Entity = value;
					if ((value != null))
					{
						value.UserFaces1.Add(this);
						this._id_docente = value.id_docente;
					}
					else
					{
						this._id_docente = default(Nullable<int>);
					}
					this.SendPropertyChanged("Docentes1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.asistencia")]
	public partial class asistencia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<System.TimeSpan> _FechaS;
		
		private System.Nullable<System.TimeSpan> _FechaE;
		
		private System.Nullable<int> _id_docente;
		
		private System.Nullable<int> _id_estado;
		
		private string _Fecha;
		
		private EntitySet<Justificacion> _Justificacion;
		
		private EntityRef<Docentes> _Docentes;
		
		private EntityRef<Estado> _Estado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnFechaSChanging(System.Nullable<System.TimeSpan> value);
    partial void OnFechaSChanged();
    partial void OnFechaEChanging(System.Nullable<System.TimeSpan> value);
    partial void OnFechaEChanged();
    partial void Onid_docenteChanging(System.Nullable<int> value);
    partial void Onid_docenteChanged();
    partial void Onid_estadoChanging(System.Nullable<int> value);
    partial void Onid_estadoChanged();
    partial void OnFechaChanging(string value);
    partial void OnFechaChanged();
    #endregion
		
		public asistencia()
		{
			this._Justificacion = new EntitySet<Justificacion>(new Action<Justificacion>(this.attach_Justificacion), new Action<Justificacion>(this.detach_Justificacion));
			this._Docentes = default(EntityRef<Docentes>);
			this._Estado = default(EntityRef<Estado>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaS", DbType="Time")]
		public System.Nullable<System.TimeSpan> FechaS
		{
			get
			{
				return this._FechaS;
			}
			set
			{
				if ((this._FechaS != value))
				{
					this.OnFechaSChanging(value);
					this.SendPropertyChanging();
					this._FechaS = value;
					this.SendPropertyChanged("FechaS");
					this.OnFechaSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaE", DbType="Time")]
		public System.Nullable<System.TimeSpan> FechaE
		{
			get
			{
				return this._FechaE;
			}
			set
			{
				if ((this._FechaE != value))
				{
					this.OnFechaEChanging(value);
					this.SendPropertyChanging();
					this._FechaE = value;
					this.SendPropertyChanged("FechaE");
					this.OnFechaEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_docente", DbType="Int")]
		public System.Nullable<int> id_docente
		{
			get
			{
				return this._id_docente;
			}
			set
			{
				if ((this._id_docente != value))
				{
					if (this._Docentes.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_docenteChanging(value);
					this.SendPropertyChanging();
					this._id_docente = value;
					this.SendPropertyChanged("id_docente");
					this.Onid_docenteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_estado", DbType="Int")]
		public System.Nullable<int> id_estado
		{
			get
			{
				return this._id_estado;
			}
			set
			{
				if ((this._id_estado != value))
				{
					if (this._Estado.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_estadoChanging(value);
					this.SendPropertyChanging();
					this._id_estado = value;
					this.SendPropertyChanged("id_estado");
					this.Onid_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="NVarChar(50)")]
		public string Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="asistencia_Justificacion", Storage="_Justificacion", ThisKey="Id", OtherKey="id_asistencia")]
		public EntitySet<Justificacion> Justificacion
		{
			get
			{
				return this._Justificacion;
			}
			set
			{
				this._Justificacion.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Docentes_asistencia", Storage="_Docentes", ThisKey="id_docente", OtherKey="id_docente", IsForeignKey=true)]
		public Docentes Docentes
		{
			get
			{
				return this._Docentes.Entity;
			}
			set
			{
				Docentes previousValue = this._Docentes.Entity;
				if (((previousValue != value) 
							|| (this._Docentes.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Docentes.Entity = null;
						previousValue.asistencia.Remove(this);
					}
					this._Docentes.Entity = value;
					if ((value != null))
					{
						value.asistencia.Add(this);
						this._id_docente = value.id_docente;
					}
					else
					{
						this._id_docente = default(Nullable<int>);
					}
					this.SendPropertyChanged("Docentes");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Estado_asistencia", Storage="_Estado", ThisKey="id_estado", OtherKey="Id", IsForeignKey=true)]
		public Estado Estado
		{
			get
			{
				return this._Estado.Entity;
			}
			set
			{
				Estado previousValue = this._Estado.Entity;
				if (((previousValue != value) 
							|| (this._Estado.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Estado.Entity = null;
						previousValue.asistencia.Remove(this);
					}
					this._Estado.Entity = value;
					if ((value != null))
					{
						value.asistencia.Add(this);
						this._id_estado = value.Id;
					}
					else
					{
						this._id_estado = default(Nullable<int>);
					}
					this.SendPropertyChanged("Estado");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Justificacion(Justificacion entity)
		{
			this.SendPropertyChanging();
			entity.asistencia = this;
		}
		
		private void detach_Justificacion(Justificacion entity)
		{
			this.SendPropertyChanging();
			entity.asistencia = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Docentes")]
	public partial class Docentes : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_docente;
		
		private string _Nombre;
		
		private string _Identificador;
		
		private EntitySet<UserFaces> _UserFaces;
		
		private EntitySet<UserFaces> _UserFaces1;
		
		private EntitySet<asistencia> _asistencia;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_docenteChanging(int value);
    partial void Onid_docenteChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnIdentificadorChanging(string value);
    partial void OnIdentificadorChanged();
    #endregion
		
		public Docentes()
		{
			this._UserFaces = new EntitySet<UserFaces>(new Action<UserFaces>(this.attach_UserFaces), new Action<UserFaces>(this.detach_UserFaces));
			this._UserFaces1 = new EntitySet<UserFaces>(new Action<UserFaces>(this.attach_UserFaces1), new Action<UserFaces>(this.detach_UserFaces1));
			this._asistencia = new EntitySet<asistencia>(new Action<asistencia>(this.attach_asistencia), new Action<asistencia>(this.detach_asistencia));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_docente", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_docente
		{
			get
			{
				return this._id_docente;
			}
			set
			{
				if ((this._id_docente != value))
				{
					this.Onid_docenteChanging(value);
					this.SendPropertyChanging();
					this._id_docente = value;
					this.SendPropertyChanged("id_docente");
					this.Onid_docenteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(50)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Identificador", DbType="NVarChar(60)")]
		public string Identificador
		{
			get
			{
				return this._Identificador;
			}
			set
			{
				if ((this._Identificador != value))
				{
					this.OnIdentificadorChanging(value);
					this.SendPropertyChanging();
					this._Identificador = value;
					this.SendPropertyChanged("Identificador");
					this.OnIdentificadorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Docentes_UserFaces", Storage="_UserFaces", ThisKey="id_docente", OtherKey="id_docente")]
		public EntitySet<UserFaces> UserFaces
		{
			get
			{
				return this._UserFaces;
			}
			set
			{
				this._UserFaces.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Docentes_UserFaces1", Storage="_UserFaces1", ThisKey="id_docente", OtherKey="id_docente")]
		public EntitySet<UserFaces> UserFaces1
		{
			get
			{
				return this._UserFaces1;
			}
			set
			{
				this._UserFaces1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Docentes_asistencia", Storage="_asistencia", ThisKey="id_docente", OtherKey="id_docente")]
		public EntitySet<asistencia> asistencia
		{
			get
			{
				return this._asistencia;
			}
			set
			{
				this._asistencia.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_UserFaces(UserFaces entity)
		{
			this.SendPropertyChanging();
			entity.Docentes = this;
		}
		
		private void detach_UserFaces(UserFaces entity)
		{
			this.SendPropertyChanging();
			entity.Docentes = null;
		}
		
		private void attach_UserFaces1(UserFaces entity)
		{
			this.SendPropertyChanging();
			entity.Docentes1 = this;
		}
		
		private void detach_UserFaces1(UserFaces entity)
		{
			this.SendPropertyChanging();
			entity.Docentes1 = null;
		}
		
		private void attach_asistencia(asistencia entity)
		{
			this.SendPropertyChanging();
			entity.Docentes = this;
		}
		
		private void detach_asistencia(asistencia entity)
		{
			this.SendPropertyChanging();
			entity.Docentes = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Estado")]
	public partial class Estado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Estado1;
		
		private EntitySet<asistencia> _asistencia;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnEstado1Changing(string value);
    partial void OnEstado1Changed();
    #endregion
		
		public Estado()
		{
			this._asistencia = new EntitySet<asistencia>(new Action<asistencia>(this.attach_asistencia), new Action<asistencia>(this.detach_asistencia));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Estado", Storage="_Estado1", DbType="VarChar(50)")]
		public string Estado1
		{
			get
			{
				return this._Estado1;
			}
			set
			{
				if ((this._Estado1 != value))
				{
					this.OnEstado1Changing(value);
					this.SendPropertyChanging();
					this._Estado1 = value;
					this.SendPropertyChanged("Estado1");
					this.OnEstado1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Estado_asistencia", Storage="_asistencia", ThisKey="Id", OtherKey="id_estado")]
		public EntitySet<asistencia> asistencia
		{
			get
			{
				return this._asistencia;
			}
			set
			{
				this._asistencia.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_asistencia(asistencia entity)
		{
			this.SendPropertyChanging();
			entity.Estado = this;
		}
		
		private void detach_asistencia(asistencia entity)
		{
			this.SendPropertyChanging();
			entity.Estado = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.fecha")]
	public partial class fecha : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _dy;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OndyChanging(string value);
    partial void OndyChanged();
    #endregion
		
		public fecha()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dy", DbType="NVarChar(50)")]
		public string dy
		{
			get
			{
				return this._dy;
			}
			set
			{
				if ((this._dy != value))
				{
					this.OndyChanging(value);
					this.SendPropertyChanging();
					this._dy = value;
					this.SendPropertyChanged("dy");
					this.OndyChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Justificacion")]
	public partial class Justificacion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_justificar;
		
		private System.Nullable<int> _id_asistencia;
		
		private string _Razon;
		
		private EntityRef<asistencia> _asistencia;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_justificarChanging(int value);
    partial void Onid_justificarChanged();
    partial void Onid_asistenciaChanging(System.Nullable<int> value);
    partial void Onid_asistenciaChanged();
    partial void OnRazonChanging(string value);
    partial void OnRazonChanged();
    #endregion
		
		public Justificacion()
		{
			this._asistencia = default(EntityRef<asistencia>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_justificar", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_justificar
		{
			get
			{
				return this._id_justificar;
			}
			set
			{
				if ((this._id_justificar != value))
				{
					this.Onid_justificarChanging(value);
					this.SendPropertyChanging();
					this._id_justificar = value;
					this.SendPropertyChanged("id_justificar");
					this.Onid_justificarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_asistencia", DbType="Int")]
		public System.Nullable<int> id_asistencia
		{
			get
			{
				return this._id_asistencia;
			}
			set
			{
				if ((this._id_asistencia != value))
				{
					if (this._asistencia.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_asistenciaChanging(value);
					this.SendPropertyChanging();
					this._id_asistencia = value;
					this.SendPropertyChanged("id_asistencia");
					this.Onid_asistenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Razon", DbType="NVarChar(MAX)")]
		public string Razon
		{
			get
			{
				return this._Razon;
			}
			set
			{
				if ((this._Razon != value))
				{
					this.OnRazonChanging(value);
					this.SendPropertyChanging();
					this._Razon = value;
					this.SendPropertyChanged("Razon");
					this.OnRazonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="asistencia_Justificacion", Storage="_asistencia", ThisKey="id_asistencia", OtherKey="Id", IsForeignKey=true)]
		public asistencia asistencia
		{
			get
			{
				return this._asistencia.Entity;
			}
			set
			{
				asistencia previousValue = this._asistencia.Entity;
				if (((previousValue != value) 
							|| (this._asistencia.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._asistencia.Entity = null;
						previousValue.Justificacion.Remove(this);
					}
					this._asistencia.Entity = value;
					if ((value != null))
					{
						value.Justificacion.Add(this);
						this._id_asistencia = value.Id;
					}
					else
					{
						this._id_asistencia = default(Nullable<int>);
					}
					this.SendPropertyChanged("asistencia");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[Asistencia View]")]
	public partial class Asistencia_View
	{
		
		private string _Nombre;
		
		private int _IdImage;
		
		private System.Data.Linq.Binary _Face;
		
		private System.Nullable<int> _id_docente;
		
		public Asistencia_View()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(50)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdImage", DbType="Int NOT NULL")]
		public int IdImage
		{
			get
			{
				return this._IdImage;
			}
			set
			{
				if ((this._IdImage != value))
				{
					this._IdImage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Face", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Face
		{
			get
			{
				return this._Face;
			}
			set
			{
				if ((this._Face != value))
				{
					this._Face = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_docente", DbType="Int")]
		public System.Nullable<int> id_docente
		{
			get
			{
				return this._id_docente;
			}
			set
			{
				if ((this._id_docente != value))
				{
					this._id_docente = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Info_docente")]
	public partial class Info_docente
	{
		
		private string _Docente;
		
		private int _id_docente;
		
		public Info_docente()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Docente", DbType="NVarChar(50)")]
		public string Docente
		{
			get
			{
				return this._Docente;
			}
			set
			{
				if ((this._Docente != value))
				{
					this._Docente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_docente", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id_docente
		{
			get
			{
				return this._id_docente;
			}
			set
			{
				if ((this._id_docente != value))
				{
					this._id_docente = value;
				}
			}
		}
	}
	
	public partial class procedimientoResult
	{
		
		private int _id_docente;
		
		private string _Nombre;
		
		private int _IdImage;
		
		private System.Data.Linq.Binary _Face;
		
		private string _Fecha;
		
		public procedimientoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_docente", DbType="Int NOT NULL")]
		public int id_docente
		{
			get
			{
				return this._id_docente;
			}
			set
			{
				if ((this._id_docente != value))
				{
					this._id_docente = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(50)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdImage", DbType="Int NOT NULL")]
		public int IdImage
		{
			get
			{
				return this._IdImage;
			}
			set
			{
				if ((this._IdImage != value))
				{
					this._IdImage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Face", DbType="VarBinary(MAX)")]
		public System.Data.Linq.Binary Face
		{
			get
			{
				return this._Face;
			}
			set
			{
				if ((this._Face != value))
				{
					this._Face = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="NVarChar(50)")]
		public string Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this._Fecha = value;
				}
			}
		}
	}
	
	public partial class procedimiento2Result
	{
		
		private int _IdImage;
		
		private System.Data.Linq.Binary _Face;
		
		private int _Id;
		
		private System.Nullable<System.TimeSpan> _FechaS;
		
		private System.Nullable<System.TimeSpan> _FechaE;
		
		private string _Fecha;
		
		private string _Nombre;
		
		private string _Identificador;
		
		public procedimiento2Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdImage", DbType="Int NOT NULL")]
		public int IdImage
		{
			get
			{
				return this._IdImage;
			}
			set
			{
				if ((this._IdImage != value))
				{
					this._IdImage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Face", DbType="VarBinary(MAX)")]
		public System.Data.Linq.Binary Face
		{
			get
			{
				return this._Face;
			}
			set
			{
				if ((this._Face != value))
				{
					this._Face = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaS", DbType="Time")]
		public System.Nullable<System.TimeSpan> FechaS
		{
			get
			{
				return this._FechaS;
			}
			set
			{
				if ((this._FechaS != value))
				{
					this._FechaS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaE", DbType="Time")]
		public System.Nullable<System.TimeSpan> FechaE
		{
			get
			{
				return this._FechaE;
			}
			set
			{
				if ((this._FechaE != value))
				{
					this._FechaE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="NVarChar(50)")]
		public string Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this._Fecha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(50)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Identificador", DbType="NVarChar(60)")]
		public string Identificador
		{
			get
			{
				return this._Identificador;
			}
			set
			{
				if ((this._Identificador != value))
				{
					this._Identificador = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
